#!/usr/bin/env bash
#
# Author: Massimo Cannavo <massimo5cannavo@gmail.com>
# Date:   Tue Jun 19 16:16:02 PDT 2018
#
# Script to automate deployment of Rancher cluster.

readonly PROGNAME=$(basename $0)
readonly ARGS="$@"

readonly ROOT=0
readonly FAILURE=1

check_root() {
  if [[ $EUID -ne $ROOT ]]; then
    echo "${PROGNAME}: run as root" >&2
    exit $FAILURE
  fi
}

check_args() {
  while getopts ":d" arg; do
    case $arg in
      d)
        ./rke --config rancher-cluster.yml
        exit
        ;;
      \?)
        echo "${PROGNAME}: invalid argument -$OPTARG" >&2
        exit $FAILURE
        ;;
      esac
  done
}

install_rke() {
  local -r ver="v0.1.7"

  curl --fail --show-error --location \
    "https://github.com/rancher/rke/releases/download/$ver/rke_linux-amd64" \
    --output ./rke

  chmod +x ./rke
}

main() {
  check_root
  check_args $ARGS

  install_rke
}

main
