#!/usr/bin/env bash
#
# File: deploy-cluster
#
# Author: Massimo Cannavo <massimo5cannavo@gmail.com>
# Date:   Tue Jun 19 16:16:02 PDT 2018
#
# Script to automate deployment of Rancher cluster.

readonly PROGNAME=$(basename $0)

readonly ROOT=0
readonly FAILURE=1

check_root() {
  if [[ $EUID -ne $ROOT ]]; then
    echo "${PROGNAME}: run as root" >&2
    exit $FAILURE
  fi
}

install_rke() {
  local -r ver="v0.1.7"

  curl --fail --show-error --location \
    "https://github.com/rancher/rke/releases/download/$ver/rke_linux-amd64" \
    --output ./rke

  chmod +x ./rke
}

deploy_cluster() {
  ./rke up --config rancher-cluster.yml
}

main() {
  check_root

  if [[ ! -x ./rke ]]; then
    install_rke
  fi

  deploy_cluster
}

main
