#!/usr/bin/env bash
#
# File: deploy-cluster
#
# Author: Massimo Cannavo <massimo5cannavo@gmail.com>
# Date:   Tue Jun 19 16:16:02 PDT 2018
#
# Script to automate deployment of Rancher cluster.

readonly PROGNAME=$(basename $0)

readonly ROOT=0
readonly FAILURE=1

readonly RED="\033[0;31m"
readonly RESET="\033[0m"

check_root() {
  if [[ $EUID -ne $ROOT ]]; then
    printf "${RED}${PROGNAME}${RESET}: run as root\n" >&2
    exit $FAILURE
  fi
}

is_installed() {
  local -r pkg=${1:null}
  return `which $pkg > /dev/null`
}

install_rke() {
  local -r ver="v0.1.7"

  curl --fail --show-error --location \
    "https://github.com/rancher/rke/releases/download/$ver/rke_linux-amd64" \
    --output /usr/local/bin/rke

  chmod +x /usr/local/bin/rke
}

deploy_cluster() {
  rke up --config rancher-cluster.yml
}

main() {
  check_root

  if ! is_installed "rke"; then
    install_rke
  fi

  deploy_cluster
}

main
