#!/usr/bin/env bash
#
# File: config-rancher-cli
#
# Author: Massimo Cannavo <massimo5cannavo@gmail.com>
# Date:   Sun Jun 24 13:47:49 PDT 2018
#
# Script to automate config of Rancher CLI.

readonly PROGNAME=$(basename $0)

readonly ROOT=0
readonly FAILURE=1

readonly RED="\033[0;31m"
readonly RESET="\033[0m"

check_root() {
  if [[ $EUID -ne $ROOT ]]; then
    printf "${RED}${PROGNAME}${RESET}: run as root\n" >&2
    exit $FAILURE
  fi
}

is_installed() {
  local -r pkg=${1:null}
  return `which $pkg > /dev/null`
}

install_kubectl() {
  local -r ver="v1.10.5"

  curl --fail --show-error --location --remote-name \
    https://storage.googleapis.com/kubernetes-release/release/$ver/bin/linux/amd64/kubectl

  mv kubectl /usr/local/bin/kubectl
  chmod +x /usr/local/bin/kubectl
}

config_cli() {
  local url=""
  local token=""

  echo ""

  read -p "Enter endpoint url: " url
  read -p "Enter api token: " token

  echo ""

  docker-compose -f rancher-cli-compose.yml run --rm rancher-cli \
    login --token $token $url

  docker-compose -f rancher-cli-compose.yml run --rm rancher-cli nodes
}

main() {
  check_root

  if ! is_installed "kubectl"; then
    install_kubectl
  fi

  config_cli
}

main
