#!/usr/bin/env bash
#
# File: config-rancher-cli
#
# Author: Massimo Cannavo <massimo5cannavo@gmail.com>
# Date:   Sun Jun 24 13:47:49 PDT 2018
#
# Script to automate config of Rancher CLI.

readonly PROGNAME=$(basename $0)

readonly ROOT=0
readonly FAILURE=1

check_root() {
  if [[ $EUID -ne $ROOT ]]; then
    echo "${PROGNAME}: run as root" >&2
    exit $FAILURE
  fi
}

install_kubectl() {
  local -r ver="v1.10.5"

  curl --fail --show-error --location --remote-name \
    https://storage.googleapis.com/kubernetes-release/release/$ver/bin/linux/amd64/kubectl

  chmod +x ./kubectl
}

config_cli() {
  local url=""
  local token=""

  echo ""

  read -p "Enter endpoint url: " url
  read -p "Enter api token: " token

  echo ""

  docker-compose -f rancher-cli-compose.yml run --rm rancher-cli \
    login --token $token $url

  docker-compose -f rancher-cli-compose.yml run --rm rancher-cli nodes
}

main() {
  check_root

  if [[ ! -x ./kubectl ]]; then
    install_kubectl
  fi

  config_cli
}

main
