#!/usr/bin/env bash
#
# File: config-droplet
#
# Author: Massimo Cannavo <massimo5cannavo@gmail.com>
# Date:   Tue Jun 19 13:56:22 PDT 2018
#
# Script to automate configuration of a droplet on DigitalOcean.

readonly PROGNAME=$(basename $0)

readonly ROOT=0
readonly FAILURE=1

check_root() {
  if [[ $EUID -ne $ROOT ]]; then
    echo "${PROGNAME}: run as root" >&2
    exit $FAILURE
  fi
}

install_docker() {
  local -r docker_gpg="https://download.docker.com/linux/ubuntu/gpg"
  local -r docker_repo="https://download.docker.com/linux/ubuntu"
  local -r docker_ver="17.03.2~ce-0~ubuntu-xenial"

  apt-get update

  apt-get install --yes \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common

  curl --fail --show-error --location $docker_gpg | apt-key add -

  add-apt-repository \
    "deb [arch=amd64] $docker_repo \
    $(lsb_release --codename --short) \
    stable"

  apt-get update
  apt-get install --yes docker-ce=$docker_ver
}

install_compose() {
  local -r ver="1.21.1"
  local -r arch=`uname --kernel-name`-`uname --machine`

  curl --fail --show-error --location \
    "https://github.com/docker/compose/releases/download/$ver/docker-compose-$arch" \
    --output /usr/local/bin/docker-compose

  chmod +x /usr/local/bin/docker-compose
}

generate_ssh() {
  ssh-keygen -f ~/.ssh/id_rsa -t rsa -N ''
  cat ~/.ssh/id_rsa.pub
}

main() {
  check_root

  install_docker
  install_compose

  generate_ssh
}

main
